### ISSUE TITLE
BUG - NwItem.Create does not create the item if the target inventory is a NwPlayer

### ISSUE THREAD

**Issue by Chimerik** [nwn-dotnet/NWN.Managed#142]
If this line is used : 

NwItem contract = NwItem.Create("skillbookgeneriq", player.oid, 1, "private_contract");

No item is created.

If this line is used: 

NwItem contract = NwItem.Create("skillbookgeneriq", player.oid.Location, false, "private_contract");

The item is correctly created on the ground at player Location.

The item is not a stackable item.

The item creation only seems to fail when trying to create directly an item in a NwPlayer inventory. Creating it in a placeable inventory works fine.

**Comment by urothis** [comment]
@Chimerik is this still an ongoing issue? 
I noticed the "player.oid" usage and was confused.

**Comment by milliorn** [comment]
Working example I have here. I would check your object that you are creating this on. As for the stack size my example shows how you can do this and what your doing wrong.

https://github.com/milliorn/Eldritch-Warrior/blob/7e4d400318cab9fbced1348c91505212d77ba675/src/Services/ActivateItem/SpellBook.cs#L302

**Comment by Chimerik** [comment]
It works now. It was probably fixed by a previous change.

The only remaining issue I have with NwItem.Create() is that it's not possible to create stacks when using a location as the parameter.
