### ISSUE TITLE
NWScript Functions

### ISSUE THREAD

**Issue by Jorteck** [nwn-dotnet/NWN.Managed#27]
The following NWScript functions have yet to be mapped to an API:

- [x] [ActionCastFakeSpellAtLocation](https://nwnlexicon.com/index.php?title=ActionCastFakeSpellAtLocation)
- [x] [ActionCastFakeSpellAtObject](https://nwnlexicon.com/index.php?title=ActionCastFakeSpellAtObject)
- [x] [ActionCounterSpell](https://nwnlexicon.com/index.php?title=ActionCounterSpell)
- [x] [ActionEquipMostDamagingMelee](https://nwnlexicon.com/index.php?title=ActionEquipMostDamagingMelee)
- [x] [ActionEquipMostDamagingRanged](https://nwnlexicon.com/index.php?title=ActionEquipMostDamagingRanged)
- [x] [ActionEquipMostEffectiveArmor](https://nwnlexicon.com/index.php?title=ActionEquipMostEffectiveArmor)
- [x] [ActionExamine](https://nwnlexicon.com/index.php?title=ActionExamine)
- [x] [ActionForceMoveToLocation](https://nwnlexicon.com/index.php?title=ActionForceMoveToLocation)
- [x] [ActionForceMoveToObject](https://nwnlexicon.com/index.php?title=ActionForceMoveToObject)
- [x] [ActionInteractObject](https://nwnlexicon.com/index.php?title=ActionInteractObject)
- [x] [ActionJumpToLocation](https://nwnlexicon.com/index.php?title=ActionJumpToLocation)
- [x] [ActionJumpToObject](https://nwnlexicon.com/index.php?title=ActionJumpToObject)
- [x] [ActionLockObject](https://nwnlexicon.com/index.php?title=ActionLockObject)
- [ ] [ActionPauseConversation](https://nwnlexicon.com/index.php?title=ActionPauseConversation)
- [x] [ActionRest](https://nwnlexicon.com/index.php?title=ActionRest)
- [ ] [ActionResumeConversation](https://nwnlexicon.com/index.php?title=ActionResumeConversation)
- [ ] [ActionSpeakStringByStrRef](https://nwnlexicon.com/index.php?title=ActionSpeakStringByStrRef)
- [x] ~[ActionTakeItem](https://nwnlexicon.com/index.php?title=ActionTakeItem)~ `NWCreature.GiveItem`
- [x] [ActionUnlockObject](https://nwnlexicon.com/index.php?title=ActionUnlockObject)
- [x] [ActionUseFeat](https://nwnlexicon.com/index.php?title=ActionUseFeat)
- [x] [ActionUseItemAtLocation](https://nwnlexicon.com/index.php?title=ActionUseItemAtLocation)
- [x] [ActionUseItemOnObject](https://nwnlexicon.com/index.php?title=ActionUseItemOnObject)
- [x] [ActionUseSkill](https://nwnlexicon.com/index.php?title=ActionUseSkill)
- [x] [ActionUseTalentAtLocation](https://nwnlexicon.com/index.php?title=ActionUseTalentAtLocation)
- [x] [ActionUseTalentOnObject](https://nwnlexicon.com/index.php?title=ActionUseTalentOnObject)
- [x] [ActionWait](https://nwnlexicon.com/index.php?title=ActionWait)
- [x] [AddHenchman](https://nwnlexicon.com/index.php?title=AddHenchman)
- [x] [AddJournalQuestEntry](https://nwnlexicon.com/index.php?title=AddJournalQuestEntry)
- [x] [AdjustReputation](https://nwnlexicon.com/index.php?title=AdjustReputation)
- [x] [AngleToVector](https://nwnlexicon.com/index.php?title=AngleToVector)
- [ ] [ApplyEffectAtLocation](https://nwnlexicon.com/index.php?title=ApplyEffectAtLocation)
- [x] ~BadBadReplaceMeThisDoesNothing~
- [ ] [BeginConversation](https://nwnlexicon.com/index.php?title=BeginConversation)
- [x] [BlackScreen](https://nwnlexicon.com/index.php?title=BlackScreen)
- [x] [ClearPersonalReputation](https://nwnlexicon.com/index.php?title=ClearPersonalReputation)
- [x] [CopyItem](https://nwnlexicon.com/index.php?title=CopyItem)
- [x] [CopyItemAndModify](https://nwnlexicon.com/index.php?title=CopyItemAndModify)
- [ ] [CreateTrapAtLocation](https://nwnlexicon.com/index.php?title=CreateTrapAtLocation)
- [ ] [CreateTrapOnObject](https://nwnlexicon.com/index.php?title=CreateTrapOnObject)
- [x] [DayToNight](https://nwnlexicon.com/index.php?title=DayToNight)
- [x] [DecrementRemainingFeatUses](https://nwnlexicon.com/index.php?title=DecrementRemainingFeatUses)
- [ ] [DecrementRemainingSpellUses](https://nwnlexicon.com/index.php?title=DecrementRemainingSpellUses)
- [x] [DoDoorAction](https://nwnlexicon.com/index.php?title=DoDoorAction)
- [x] [DoPlaceableObjectAction](https://nwnlexicon.com/index.php?title=DoPlaceableObjectAction)
- [ ] [DoSinglePlayerAutoSave](https://nwnlexicon.com/index.php?title=DoSinglePlayerAutoSave)
- [ ] [DoWhirlwindAttack](https://nwnlexicon.com/index.php?title=DoWhirlwindAttack)
- [ ] [EffectLinkEffects](https://nwnlexicon.com/index.php?title=EffectLinkEffects)
- [ ] [EventActivateItem](https://nwnlexicon.com/index.php?title=EventActivateItem)
- [ ] [EventConversation](https://nwnlexicon.com/index.php?title=EventConversation)
- [ ] [EventSpellCastAt](https://nwnlexicon.com/index.php?title=EventSpellCastAt)
- [ ] [EventUserDefined](https://nwnlexicon.com/index.php?title=EventUserDefined)
- [ ] [ExecuteScriptChunk](https://nwnlexicon.com/index.php?title=ExecuteScriptChunk)
- [x] [FadeFromBlack](https://nwnlexicon.com/index.php?title=FadeFromBlack)
- [x] [FadeToBlack](https://nwnlexicon.com/index.php?title=FadeToBlack)
- [x] [FeetToMeters](https://nwnlexicon.com/index.php?title=FeetToMeters)
- [x] ~[FloatToInt](https://nwnlexicon.com/index.php?title=FloatToInt)~ Cast, or use System.Math.Round` instead.
- [x] ~[FloatToString](https://nwnlexicon.com/index.php?title=FloatToString)~ Use `float.ToString` instead.
- [x] [FloatingTextStrRefOnCreature](https://nwnlexicon.com/index.php?title=FloatingTextStrRefOnCreature)
- [x] [FloatingTextStringOnCreature](https://nwnlexicon.com/index.php?title=FloatingTextStringOnCreature)
- [x] [GetAILevel](https://nwnlexicon.com/index.php?title=GetAILevel)
- [x] [GetAbilityModifier](https://nwnlexicon.com/index.php?title=GetAbilityModifier)
- [x] [GetActionMode](https://nwnlexicon.com/index.php?title=GetActionMode)
- [x] [GetAnimalCompanionCreatureType](https://nwnlexicon.com/index.php?title=GetAnimalCompanionCreatureType)
- [x] [GetAnimalCompanionName](https://nwnlexicon.com/index.php?title=GetAnimalCompanionName)
- [x] [GetAppearanceType](https://nwnlexicon.com/index.php?title=GetAppearanceType)
- [x] [GetArcaneSpellFailure](https://nwnlexicon.com/index.php?title=GetArcaneSpellFailure)
- [x] [GetAssociate](https://nwnlexicon.com/index.php?title=GetAssociate)
- [ ] [GetClickingObject](https://nwnlexicon.com/index.php?title=GetClickingObject)
- [x] [GetCreatureBodyPart](https://nwnlexicon.com/index.php?title=GetCreatureBodyPart)
- [x] [GetCreatureExploresMinimap](https://nwnlexicon.com/index.php?title=GetCreatureExploresMinimap)
- [x] [GetCreatureStartingPackage](https://nwnlexicon.com/index.php?title=GetCreatureStartingPackage)
- [x] [GetCreatureTailType](https://nwnlexicon.com/index.php?title=GetCreatureTailType)
- [x] [GetCreatureTalentBest](https://nwnlexicon.com/index.php?title=GetCreatureTalentBest)
- [x] [GetCreatureTalentRandom](https://nwnlexicon.com/index.php?title=GetCreatureTalentRandom)
- [x] [GetCreatureWingType](https://nwnlexicon.com/index.php?title=GetCreatureWingType)
- [x] [GetCutsceneCameraMoveRate](https://nwnlexicon.com/index.php?title=GetCutsceneCameraMoveRate)
- [x] [GetCutsceneMode](https://nwnlexicon.com/index.php?title=GetCutsceneMode)
- [ ] [GetDamageDealtByType](https://nwnlexicon.com/index.php?title=GetDamageDealtByType)
- [x] [GetDefensiveCastingMode](https://nwnlexicon.com/index.php?title=GetDefensiveCastingMode)
- [x] [GetDetectMode](https://nwnlexicon.com/index.php?title=GetDetectMode)
- [ ] [GetDialogSoundLength](https://nwnlexicon.com/index.php?title=GetDialogSoundLength)
- [x] [GetDistanceBetween](https://nwnlexicon.com/index.php?title=GetDistanceBetween)
- [x] [GetDistanceBetweenLocations](https://nwnlexicon.com/index.php?title=GetDistanceBetweenLocations)
- [x] [GetDistanceToObject](https://nwnlexicon.com/index.php?title=GetDistanceToObject)
- [ ] [GetEffectCasterLevel](https://nwnlexicon.com/index.php?title=GetEffectCasterLevel)
- [ ] [GetEffectSpellId](https://nwnlexicon.com/index.php?title=GetEffectSpellId)
- [x] [GetFamiliarCreatureType](https://nwnlexicon.com/index.php?title=GetFamiliarCreatureType)
- [x] [GetFamiliarName](https://nwnlexicon.com/index.php?title=GetFamiliarName)
- [x] [GetFootstepType](https://nwnlexicon.com/index.php?title=GetFootstepType)
- [ ] [GetGoingToBeAttackedBy](https://nwnlexicon.com/index.php?title=GetGoingToBeAttackedBy)
- [x] [GetHasFeatEffect](https://nwnlexicon.com/index.php?title=GetHasFeatEffect)
- [x] [GetHasInventory](https://nwnlexicon.com/index.php?title=GetHasInventory)
- [x] [GetHasSpellEffect](https://nwnlexicon.com/index.php?title=GetHasSpellEffect)
- [ ] [GetHenchman](https://nwnlexicon.com/index.php?title=GetHenchman)
- [x] [GetHiddenWhenEquipped](https://nwnlexicon.com/index.php?title=GetHiddenWhenEquipped)
- [x] [GetIsDoorActionPossible](https://nwnlexicon.com/index.php?title=GetIsDoorActionPossible)
- [x] [GetIsEncounterCreature](https://nwnlexicon.com/index.php?title=GetIsEncounterCreature)
- [ ] [GetIsInSubArea](https://nwnlexicon.com/index.php?title=GetIsInSubArea)
- [ ] [GetIsListening](https://nwnlexicon.com/index.php?title=GetIsListening)
- [x] [GetIsPlaceableObjectActionPossible](https://nwnlexicon.com/index.php?title=GetIsPlaceableObjectActionPossi)
- [x] [GetIsReactionTypeFriendly](https://nwnlexicon.com/index.php?title=GetIsReactionTypeFriendly)
- [x] [GetIsReactionTypeHostile](https://nwnlexicon.com/index.php?title=GetIsReactionTypeHostile)
- [x] [GetIsReactionTypeNeutral](https://nwnlexicon.com/index.php?title=GetIsReactionTypeNeutral)
- [x] [GetIsWeaponEffective](https://nwnlexicon.com/index.php?title=GetIsWeaponEffective)
- [ ] [GetItemAppearance](https://nwnlexicon.com/index.php?title=GetItemAppearance)
- [x] [GetItemHasItemProperty](https://nwnlexicon.com/index.php?title=GetItemHasItemProperty)
- [x] [GetItemPropertyCostTable](https://nwnlexicon.com/index.php?title=GetItemPropertyCostTable)
- [x] [GetItemPropertyCostTableValue](https://nwnlexicon.com/index.php?title=GetItemPropertyCostTableValue)
- [ ] [GetItemPropertyParam1](https://nwnlexicon.com/index.php?title=GetItemPropertyParam1)
- [ ] [GetItemPropertyParam1Value](https://nwnlexicon.com/index.php?title=GetItemPropertyParam1Value)
- [x] [GetItemPropertyUsesPerDayRemaining](https://nwnlexicon.com/index.php?title=GetItemPropertyUsesPerDayRemain)
- [ ] [GetJournalQuestExperience](https://nwnlexicon.com/index.php?title=GetJournalQuestExperience)
- [x] [GetKeyRequiredFeedback](https://nwnlexicon.com/index.php?title=GetKeyRequiredFeedback)
- [x] [GetLastAttackMode](https://nwnlexicon.com/index.php?title=GetLastAttackMode)
- [x] [GetLastAttackType](https://nwnlexicon.com/index.php?title=GetLastAttackType)
- [x] [GetLastDisarmed](https://nwnlexicon.com/index.php?title=GetLastDisarmed)
- [x] [GetLastLocked](https://nwnlexicon.com/index.php?title=GetLastLocked)
- [x] [GetLastSpeaker](https://nwnlexicon.com/index.php?title=GetLastSpeaker)
- [x] [GetLastSpell](https://nwnlexicon.com/index.php?title=GetLastSpell)
- [x] [GetLastSpellCastClass](https://nwnlexicon.com/index.php?title=GetLastSpellCastClass)
- [x] [GetLastSpellCaster](https://nwnlexicon.com/index.php?title=GetLastSpellCaster)
- [x] [GetLastSpellHarmful](https://nwnlexicon.com/index.php?title=GetLastSpellHarmful)
- [ ] [GetLastTrapDetected](https://nwnlexicon.com/index.php?title=GetLastTrapDetected)
- [x] [GetLastWeaponUsed](https://nwnlexicon.com/index.php?title=GetLastWeaponUsed)
- [x] [GetLevelByPosition](https://nwnlexicon.com/index.php?title=GetLevelByPosition)
- [ ] [GetListenPatternNumber](https://nwnlexicon.com/index.php?title=GetListenPatternNumber)
- [ ] [GetMatchedSubstring](https://nwnlexicon.com/index.php?title=GetMatchedSubstring)
- [ ] [GetMatchedSubstringsCount](https://nwnlexicon.com/index.php?title=GetMatchedSubstringsCount)
- [ ] [GetMetaMagicFeat](https://nwnlexicon.com/index.php?title=GetMetaMagicFeat)
- [ ] [GetModuleItemAcquiredStackSize](https://nwnlexicon.com/index.php?title=GetModuleItemAcquiredStackSize)
- [ ] [GetNearestObjectByTag](https://nwnlexicon.com/index.php?title=GetNearestObjectByTag)
- [ ] [GetNearestTrapToObject](https://nwnlexicon.com/index.php?title=GetNearestTrapToObject)
- [x] [GetNumStackedItems](https://nwnlexicon.com/index.php?title=GetNumStackedItems)
- [ ] [GetObjectHeard](https://nwnlexicon.com/index.php?title=GetObjectHeard)
- [ ] [GetObjectSeen](https://nwnlexicon.com/index.php?title=GetObjectSeen)
- [ ] [GetObjectType](https://nwnlexicon.com/index.php?title=GetObjectType)
- [ ] [GetPlaceableLastClickedBy](https://nwnlexicon.com/index.php?title=GetPlaceableLastClickedBy)
- [x] [GetPortraitId](https://nwnlexicon.com/index.php?title=GetPortraitId)
- [x] ~[GetRandomUUID](https://nwnlexicon.com/index.php?title=GetRandomUUID)~ use `Guid.NewGuid()` instead.
- [ ] [GetReflexAdjustedDamage](https://nwnlexicon.com/index.php?title=GetReflexAdjustedDamage)
- [x] [GetReputation](https://nwnlexicon.com/index.php?title=GetReputation)
- [x] [GetSpellResistance](https://nwnlexicon.com/index.php?title=GetSpellResistance)
- [x] [GetStealthMode](https://nwnlexicon.com/index.php?title=GetStealthMode)
- [ ] [GetStrRefSoundDuration](https://nwnlexicon.com/index.php?title=GetStrRefSoundDuration)
- [ ] [GetStringByStrRef](https://nwnlexicon.com/index.php?title=GetStringByStrRef)
- [x] ~[GetStringLowerCase](https://nwnlexicon.com/index.php?title=GetStringLowerCase)~ use `string.ToLower` instead.
- [x] ~[GetStringUpperCase](https://nwnlexicon.com/index.php?title=GetStringUpperCase)~ use `string.ToUpper` instead.
- [x] ~[GetSubString](https://nwnlexicon.com/index.php?title=GetSubString)~ `string.Substring` instead.
- [x] [GetSurfaceMaterial](https://nwnlexicon.com/index.php?title=GetSurfaceMaterial)
- [x] [GetTileExplored](https://nwnlexicon.com/index.php?title=GetTileExplored)
- [x] [GetTileMainLight1Color](https://nwnlexicon.com/index.php?title=GetTileMainLight1Color)
- [x] [GetTileMainLight2Color](https://nwnlexicon.com/index.php?title=GetTileMainLight2Color)
- [x] [GetTileSourceLight1Color](https://nwnlexicon.com/index.php?title=GetTileSourceLight1Color)
- [x] [GetTileSourceLight2Color](https://nwnlexicon.com/index.php?title=GetTileSourceLight2Color)
- [x] [GetTurnResistanceHD](https://nwnlexicon.com/index.php?title=GetTurnResistanceHD)
- [x] [GiveXPToCreature](https://nwnlexicon.com/index.php?title=GiveXPToCreature)
- [x] [IncrementRemainingFeatUses](https://nwnlexicon.com/index.php?title=IncrementRemainingFeatUses)
- [x] ~[InsertString](https://nwnlexicon.com/index.php?title=InsertString)~ Use `string.Insert` instead.
- [x] ~[IntToFloat](https://nwnlexicon.com/index.php?title=IntToFloat)~ Implicit conversion.
- [x] ~[IntToHexString](https://nwnlexicon.com/index.php?title=IntToHexString)~ Use [Number Format Specifiers](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings?redirectedfrom=MSDN#XFormatString).
- [x] ~[IntToString](https://nwnlexicon.com/index.php?title=IntToString)~ use `int.ToString` instead.
- [x] ~[JumpToLocation](https://nwnlexicon.com/index.php?title=JumpToLocation)~ use `NwObject.Location` setter
- [x] [JumpToObject](https://nwnlexicon.com/index.php?title=JumpToObject)
- [x] [LevelUpHenchman](https://nwnlexicon.com/index.php?title=LevelUpHenchman)
- [ ] [LineOfSightObject](https://nwnlexicon.com/index.php?title=LineOfSightObject)
- [ ] [LineOfSightVector](https://nwnlexicon.com/index.php?title=LineOfSightVector)
- [x] [LockCameraDirection](https://nwnlexicon.com/index.php?title=LockCameraDirection)
- [x] [LockCameraDistance](https://nwnlexicon.com/index.php?title=LockCameraDistance)
- [x] [LockCameraPitch](https://nwnlexicon.com/index.php?title=LockCameraPitch)
- [ ] [MusicBackgroundSetDelay](https://nwnlexicon.com/index.php?title=MusicBackgroundSetDelay)
- [x] [NightToDay](https://nwnlexicon.com/index.php?title=NightToDay)
- [x] [ObjectToString](https://nwnlexicon.com/index.php?title=ObjectToString) `NwObject.ToString()`
- [x] [OpenInventory](https://nwnlexicon.com/index.php?title=OpenInventory)
- [ ] [PlaySoundByStrRef](https://nwnlexicon.com/index.php?title=PlaySoundByStrRef)
- [x] [PlayVoiceChat](https://nwnlexicon.com/index.php?title=PlayVoiceChat)
- [ ] [PopUpDeathGUIPanel](https://nwnlexicon.com/index.php?title=PopUpDeathGUIPanel)
- [ ] [PopUpGUIPanel](https://nwnlexicon.com/index.php?title=PopUpGUIPanel)
- [x] [PrintFloat](https://nwnlexicon.com/index.php?title=PrintFloat)
- [x] [PrintInteger](https://nwnlexicon.com/index.php?title=PrintInteger)
- [x] [PrintObject](https://nwnlexicon.com/index.php?title=PrintObject)
- [x] [PrintString](https://nwnlexicon.com/index.php?title=PrintString)
- [x] [PrintVector](https://nwnlexicon.com/index.php?title=PrintVector)
- [x] ~[Random](https://nwnlexicon.com/index.php?title=Random)~ Use `System.Random` instead.
- [x] [RandomName](https://nwnlexicon.com/index.php?title=RandomName)
- [ ] [RemoveHenchman](https://nwnlexicon.com/index.php?title=RemoveHenchman)
- [ ] [RemoveJournalQuestEntry](https://nwnlexicon.com/index.php?title=RemoveJournalQuestEntry)
- [ ] [RemoveSummonedAssociate](https://nwnlexicon.com/index.php?title=RemoveSummonedAssociate)
- [ ] [ReplaceObjectTexture](https://nwnlexicon.com/index.php?title=ReplaceObjectTexture)
- [x] ~Reserved899~
- [ ] [ResetMaterialShaderUniforms](https://nwnlexicon.com/index.php?title=ResetMaterialShaderUniforms)
- [ ] [ResistSpell](https://nwnlexicon.com/index.php?title=ResistSpell)
- [x] [RestoreBaseAttackBonus](https://nwnlexicon.com/index.php?title=RestoreBaseAttackBonus)
- [ ] [RestoreCameraFacing](https://nwnlexicon.com/index.php?title=RestoreCameraFacing)
- [ ] [RetrieveCampaignObject](https://nwnlexicon.com/index.php?title=RetrieveCampaignObject)
- [ ] [SendMessageToPCByStrRef](https://nwnlexicon.com/index.php?title=SendMessageToPCByStrRef)
- [x] [SetAILevel](https://nwnlexicon.com/index.php?title=SetAILevel)
- [ ] [SetAreaTransitionBMP](https://nwnlexicon.com/index.php?title=SetAreaTransitionBMP)
- [ ] [SetAreaWind](https://nwnlexicon.com/index.php?title=SetAreaWind)
- [ ] [SetAssociateListenPatterns](https://nwnlexicon.com/index.php?title=SetAssociateListenPatterns)
- [x] [SetBaseAttackBonus](https://nwnlexicon.com/index.php?title=SetBaseAttackBonus)
- [x] [SetCameraHeight](https://nwnlexicon.com/index.php?title=SetCameraHeight)
- [x] [SetCameraMode](https://nwnlexicon.com/index.php?title=SetCameraMode)
- [x] [SetCreatureAppearanceType](https://nwnlexicon.com/index.php?title=SetCreatureAppearanceType)
- [x] [SetCreatureBodyPart](https://nwnlexicon.com/index.php?title=SetCreatureBodyPart)
- [x] [SetCreatureExploresMinimap](https://nwnlexicon.com/index.php?title=SetCreatureExploresMinimap)
- [x] [SetCreatureTailType](https://nwnlexicon.com/index.php?title=SetCreatureTailType)
- [x] [SetCreatureWingType](https://nwnlexicon.com/index.php?title=SetCreatureWingType)
- [ ] [SetCustomToken](https://nwnlexicon.com/index.php?title=SetCustomToken)
- [x] [SetCutsceneCameraMoveRate](https://nwnlexicon.com/index.php?title=SetCutsceneCameraMoveRate)
- [x] [SetCutsceneMode](https://nwnlexicon.com/index.php?title=SetCutsceneMode)
- [x] [SetFootstepType](https://nwnlexicon.com/index.php?title=SetFootstepType)
- [x] [SetFortitudeSavingThrow](https://nwnlexicon.com/index.php?title=SetFortitudeSavingThrow)
- [x] [SetHiddenWhenEquipped](https://nwnlexicon.com/index.php?title=SetHiddenWhenEquipped)
- [x] [SetIsDestroyable](https://nwnlexicon.com/index.php?title=SetIsDestroyable)
- [x] [SetIsTemporaryEnemy](https://nwnlexicon.com/index.php?title=SetIsTemporaryEnemy)
- [x] [SetIsTemporaryFriend](https://nwnlexicon.com/index.php?title=SetIsTemporaryFriend)
- [x] [SetIsTemporaryNeutral](https://nwnlexicon.com/index.php?title=SetIsTemporaryNeutral)
- [ ] [SetItemPropertyUsesPerDayRemaining](https://nwnlexicon.com/index.php?title=SetItemPropertyUsesPerDayRemain)
- [x] [SetKeyRequiredFeedback](https://nwnlexicon.com/index.php?title=SetKeyRequiredFeedback)
- [ ] [SetListenPattern](https://nwnlexicon.com/index.php?title=SetListenPattern)
- [ ] [SetListening](https://nwnlexicon.com/index.php?title=SetListening)
- [ ] [SetMapPinEnabled](https://nwnlexicon.com/index.php?title=SetMapPinEnabled)
- [ ] [SetMaterialShaderUniformInt](https://nwnlexicon.com/index.php?title=SetMaterialShaderUniformInt)
- [ ] [SetMaterialShaderUniformVec4](https://nwnlexicon.com/index.php?title=SetMaterialShaderUniformVec4)
- [ ] [SetObjectMouseCursor](https://nwnlexicon.com/index.php?title=SetObjectMouseCursor)
- [ ] [SetPanelButtonFlash](https://nwnlexicon.com/index.php?title=SetPanelButtonFlash)
- [x] [SetPortraitId](https://nwnlexicon.com/index.php?title=SetPortraitId)
- [x] [SetReflexSavingThrow](https://nwnlexicon.com/index.php?title=SetReflexSavingThrow)
- [x] [SetTileExplored](https://nwnlexicon.com/index.php?title=SetTileExplored)
- [x] [SetTileMainLightColor](https://nwnlexicon.com/index.php?title=SetTileMainLightColor)
- [x] [SetTileSourceLightColor](https://nwnlexicon.com/index.php?title=SetTileSourceLightColor)
- [x] [SetWillSavingThrow](https://nwnlexicon.com/index.php?title=SetWillSavingThrow)
- [ ] [SignalEvent](https://nwnlexicon.com/index.php?title=SignalEvent)
- [ ] [SoundObjectSetPosition](https://nwnlexicon.com/index.php?title=SoundObjectSetPosition)
- [ ] [SpawnScriptDebugger](https://nwnlexicon.com/index.php?title=SpawnScriptDebugger)
- [ ] [SpeakOneLinerConversation](https://nwnlexicon.com/index.php?title=SpeakOneLinerConversation)
- [ ] [SpeakStringByStrRef](https://nwnlexicon.com/index.php?title=SpeakStringByStrRef)
- [ ] [SqlBindFloat](https://nwnlexicon.com/index.php?title=SqlBindFloat)
- [ ] [SqlBindInt](https://nwnlexicon.com/index.php?title=SqlBindInt)
- [ ] [SqlBindObject](https://nwnlexicon.com/index.php?title=SqlBindObject)
- [ ] [SqlBindString](https://nwnlexicon.com/index.php?title=SqlBindString)
- [ ] [SqlBindVector](https://nwnlexicon.com/index.php?title=SqlBindVector)
- [ ] [SqlDestroyDatabase](https://nwnlexicon.com/index.php?title=SqlDestroyDatabase)
- [ ] [SqlGetError](https://nwnlexicon.com/index.php?title=SqlGetError)
- [ ] [SqlGetFloat](https://nwnlexicon.com/index.php?title=SqlGetFloat)
- [ ] [SqlGetInt](https://nwnlexicon.com/index.php?title=SqlGetInt)
- [ ] [SqlGetObject](https://nwnlexicon.com/index.php?title=SqlGetObject)
- [ ] [SqlGetString](https://nwnlexicon.com/index.php?title=SqlGetString)
- [ ] [SqlGetVector](https://nwnlexicon.com/index.php?title=SqlGetVector)
- [ ] [SqlPrepareQueryCampaign](https://nwnlexicon.com/index.php?title=SqlPrepareQueryCampaign)
- [ ] [SqlPrepareQueryObject](https://nwnlexicon.com/index.php?title=SqlPrepareQueryObject)
- [ ] [SqlStep](https://nwnlexicon.com/index.php?title=SqlStep)
- [ ] [StartNewModule](https://nwnlexicon.com/index.php?title=StartNewModule)
- [x] [StopFade](https://nwnlexicon.com/index.php?title=StopFade)
- [ ] [StoreCameraFacing](https://nwnlexicon.com/index.php?title=StoreCameraFacing)
- [ ] [StoreCampaignObject](https://nwnlexicon.com/index.php?title=StoreCampaignObject)
- [x] [StringToFloat](https://nwnlexicon.com/index.php?title=StringToFloat) `StringExtensions.ParseFloat`
- [x] [StringToInt](https://nwnlexicon.com/index.php?title=StringToInt) `StringExtensions.ParseInt`
- [x] [SummonAnimalCompanion](https://nwnlexicon.com/index.php?title=SummonAnimalCompanion)
- [x] [SummonFamiliar](https://nwnlexicon.com/index.php?title=SummonFamiliar)
- [ ] [SurrenderToEnemies](https://nwnlexicon.com/index.php?title=SurrenderToEnemies)
- [ ] [TagItemProperty](https://nwnlexicon.com/index.php?title=TagItemProperty)
- [ ] [TestStringAgainstPattern](https://nwnlexicon.com/index.php?title=TestStringAgainstPattern)
- [x] [UnpossessFamiliar](https://nwnlexicon.com/index.php?title=UnpossessFamiliar)
- [x] [Vector](https://nwnlexicon.com/index.php?title=Vector)
- [x] [VectorMagnitude](https://nwnlexicon.com/index.php?title=VectorMagnitude)
- [x] [VectorNormalize](https://nwnlexicon.com/index.php?title=VectorNormalize)
- [x] [VectorToAngle](https://nwnlexicon.com/index.php?title=VectorToAngle)
- [ ] [VersusAlignmentEffect](https://nwnlexicon.com/index.php?title=VersusAlignmentEffect)
- [ ] [VersusRacialTypeEffect](https://nwnlexicon.com/index.php?title=VersusRacialTypeEffect)
- [ ] [VersusTrapEffect](https://nwnlexicon.com/index.php?title=VersusTrapEffect)
- [x] [YardsToMeters](https://nwnlexicon.com/index.php?title=YardsToMeters)
- [x] ~[abs](https://nwnlexicon.com/index.php?title=abs)~ Use `System.Math` instead.
- [x] ~[acos](https://nwnlexicon.com/index.php?title=acos)~ Use `System.Math` instead.
- [x] ~[asin](https://nwnlexicon.com/index.php?title=asin)~ Use `System.Math` instead.
- [x] ~[atan](https://nwnlexicon.com/index.php?title=atan)~ Use `System.Math` instead.
- [x] ~[cos](https://nwnlexicon.com/index.php?title=cos)~ Use `System.Math` instead.
- [x] [d10](https://nwnlexicon.com/index.php?title=d10): `System.Random.Roll(10)`
- [x] [d100](https://nwnlexicon.com/index.php?title=d100): `System.Random.Roll(100)`
- [x] [d12](https://nwnlexicon.com/index.php?title=d12): `System.Random.Roll(12)`
- [x] [d2](https://nwnlexicon.com/index.php?title=d2): `System.Random.Roll(2)`
- [x] [d20](https://nwnlexicon.com/index.php?title=d20): `System.Random.Roll(20)`
- [x] [d3](https://nwnlexicon.com/index.php?title=d3): `System.Random.Roll(3)`
- [x] [d4](https://nwnlexicon.com/index.php?title=d4): `System.Random.Roll(4)`
- [x] [d6](https://nwnlexicon.com/index.php?title=d6): `System.Random.Roll(6)`
- [x] [d8](https://nwnlexicon.com/index.php?title=d8): `System.Random.Roll(8)`
- [x] ~[fabs](https://nwnlexicon.com/index.php?title=fabs)~ Use `System.Math` instead.
- [x] ~[log](https://nwnlexicon.com/index.php?title=log)~ Use `System.Math` instead.
- [x] ~[pow](https://nwnlexicon.com/index.php?title=pow)~ Use `System.Math` instead.
- [x] ~[sin](https://nwnlexicon.com/index.php?title=sin)~ Use `System.Math` instead.
- [x] ~[sqrt](https://nwnlexicon.com/index.php?title=sqrt)~ Use `System.Math` instead.
- [x] ~[tan](https://nwnlexicon.com/index.php?title=tan)~ Use `System.Math` instead.

**Comment by milliorn** [comment]
I have made one pass through this list.  Can this list be updated please?

**Comment by Jorteck** [comment]
Should be up to date.

**Comment by milliorn** [comment]
Can be checked off the list.
`GetCreatureBodyPart`
`SetCreatureBodyPart`
