### ISSUE TITLE
Feature request: FindObjectsOfType()

### ISSUE THREAD

**Issue by jakkn** [nwn-dotnet/NWN.Managed#53]
Useful to register event handlers on all objects of a given type, for instance `NwStore.OnOpen` and `NwStore.OnClose`. Both Area and Module are suitable scopes for the lookup. 

Suggested (pseudo) syntax
```cs
public static IEnumerable<T> FindObjectsOfTypeIn<T>(params NwArea[] areas) where T : NwObject {}
public static IEnumerable<T> FindAllObjectsOfType<T>() where T : NwObject {} //searches NwModule
```
I don't know C# well enough to know if it's possible to use type T as a value within the function body, may need additional arguments.

**Comment by Jorteck** [comment]
Added in 8193.16.34 https://github.com/nwn-dotnet/NWN.Managed/commit/cc13843c64e404cb0ab7728835e09c795d8d4094.
